package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Kind;
import test.model.KindExample;

public interface KindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int countByExample(KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int deleteByExample(KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int deleteByPrimaryKey(Integer kind_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int insert(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int insertSelective(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    List<Kind> selectByExample(KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    Kind selectByPrimaryKey(Integer kind_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") Kind record, @Param("example") KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int updateByExample(@Param("record") Kind record, @Param("example") KindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int updateByPrimaryKeySelective(Kind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int updateByPrimaryKey(Kind record);
}