package test.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import test.model.Picture;
import test.model.PictureExample;

public interface PictureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int countByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int deleteByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int deleteByPrimaryKey(Integer pict_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int insert(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int insertSelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    List<Picture> selectByExample(PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    Picture selectByPrimaryKey(Integer pict_id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int updateByExampleSelective(@Param("record") Picture record, @Param("example") PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int updateByExample(@Param("record") Picture record, @Param("example") PictureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int updateByPrimaryKeySelective(Picture record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table picture
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    int updateByPrimaryKey(Picture record);
}