package test.model;

import java.util.ArrayList;
import java.util.List;

public class KindExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public KindExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andKind_idIsNull() {
            addCriterion("kind_id is null");
            return (Criteria) this;
        }

        public Criteria andKind_idIsNotNull() {
            addCriterion("kind_id is not null");
            return (Criteria) this;
        }

        public Criteria andKind_idEqualTo(Integer value) {
            addCriterion("kind_id =", value, "kind_id");
            return (Criteria) this;
        }

        public Criteria andKind_idNotEqualTo(Integer value) {
            addCriterion("kind_id <>", value, "kind_id");
            return (Criteria) this;
        }

        public Criteria andKind_idGreaterThan(Integer value) {
            addCriterion("kind_id >", value, "kind_id");
            return (Criteria) this;
        }

        public Criteria andKind_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("kind_id >=", value, "kind_id");
            return (Criteria) this;
        }

        public Criteria andKind_idLessThan(Integer value) {
            addCriterion("kind_id <", value, "kind_id");
            return (Criteria) this;
        }

        public Criteria andKind_idLessThanOrEqualTo(Integer value) {
            addCriterion("kind_id <=", value, "kind_id");
            return (Criteria) this;
        }

        public Criteria andKind_idIn(List<Integer> values) {
            addCriterion("kind_id in", values, "kind_id");
            return (Criteria) this;
        }

        public Criteria andKind_idNotIn(List<Integer> values) {
            addCriterion("kind_id not in", values, "kind_id");
            return (Criteria) this;
        }

        public Criteria andKind_idBetween(Integer value1, Integer value2) {
            addCriterion("kind_id between", value1, value2, "kind_id");
            return (Criteria) this;
        }

        public Criteria andKind_idNotBetween(Integer value1, Integer value2) {
            addCriterion("kind_id not between", value1, value2, "kind_id");
            return (Criteria) this;
        }

        public Criteria andKind_nameIsNull() {
            addCriterion("kind_name is null");
            return (Criteria) this;
        }

        public Criteria andKind_nameIsNotNull() {
            addCriterion("kind_name is not null");
            return (Criteria) this;
        }

        public Criteria andKind_nameEqualTo(String value) {
            addCriterion("kind_name =", value, "kind_name");
            return (Criteria) this;
        }

        public Criteria andKind_nameNotEqualTo(String value) {
            addCriterion("kind_name <>", value, "kind_name");
            return (Criteria) this;
        }

        public Criteria andKind_nameGreaterThan(String value) {
            addCriterion("kind_name >", value, "kind_name");
            return (Criteria) this;
        }

        public Criteria andKind_nameGreaterThanOrEqualTo(String value) {
            addCriterion("kind_name >=", value, "kind_name");
            return (Criteria) this;
        }

        public Criteria andKind_nameLessThan(String value) {
            addCriterion("kind_name <", value, "kind_name");
            return (Criteria) this;
        }

        public Criteria andKind_nameLessThanOrEqualTo(String value) {
            addCriterion("kind_name <=", value, "kind_name");
            return (Criteria) this;
        }

        public Criteria andKind_nameLike(String value) {
            addCriterion("kind_name like", value, "kind_name");
            return (Criteria) this;
        }

        public Criteria andKind_nameNotLike(String value) {
            addCriterion("kind_name not like", value, "kind_name");
            return (Criteria) this;
        }

        public Criteria andKind_nameIn(List<String> values) {
            addCriterion("kind_name in", values, "kind_name");
            return (Criteria) this;
        }

        public Criteria andKind_nameNotIn(List<String> values) {
            addCriterion("kind_name not in", values, "kind_name");
            return (Criteria) this;
        }

        public Criteria andKind_nameBetween(String value1, String value2) {
            addCriterion("kind_name between", value1, value2, "kind_name");
            return (Criteria) this;
        }

        public Criteria andKind_nameNotBetween(String value1, String value2) {
            addCriterion("kind_name not between", value1, value2, "kind_name");
            return (Criteria) this;
        }

        public Criteria andIs_parentIsNull() {
            addCriterion("is_parent is null");
            return (Criteria) this;
        }

        public Criteria andIs_parentIsNotNull() {
            addCriterion("is_parent is not null");
            return (Criteria) this;
        }

        public Criteria andIs_parentEqualTo(Boolean value) {
            addCriterion("is_parent =", value, "is_parent");
            return (Criteria) this;
        }

        public Criteria andIs_parentNotEqualTo(Boolean value) {
            addCriterion("is_parent <>", value, "is_parent");
            return (Criteria) this;
        }

        public Criteria andIs_parentGreaterThan(Boolean value) {
            addCriterion("is_parent >", value, "is_parent");
            return (Criteria) this;
        }

        public Criteria andIs_parentGreaterThanOrEqualTo(Boolean value) {
            addCriterion("is_parent >=", value, "is_parent");
            return (Criteria) this;
        }

        public Criteria andIs_parentLessThan(Boolean value) {
            addCriterion("is_parent <", value, "is_parent");
            return (Criteria) this;
        }

        public Criteria andIs_parentLessThanOrEqualTo(Boolean value) {
            addCriterion("is_parent <=", value, "is_parent");
            return (Criteria) this;
        }

        public Criteria andIs_parentIn(List<Boolean> values) {
            addCriterion("is_parent in", values, "is_parent");
            return (Criteria) this;
        }

        public Criteria andIs_parentNotIn(List<Boolean> values) {
            addCriterion("is_parent not in", values, "is_parent");
            return (Criteria) this;
        }

        public Criteria andIs_parentBetween(Boolean value1, Boolean value2) {
            addCriterion("is_parent between", value1, value2, "is_parent");
            return (Criteria) this;
        }

        public Criteria andIs_parentNotBetween(Boolean value1, Boolean value2) {
            addCriterion("is_parent not between", value1, value2, "is_parent");
            return (Criteria) this;
        }

        public Criteria andParent_idIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParent_idIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParent_idEqualTo(Integer value) {
            addCriterion("parent_id =", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotEqualTo(Integer value) {
            addCriterion("parent_id <>", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idGreaterThan(Integer value) {
            addCriterion("parent_id >", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("parent_id >=", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idLessThan(Integer value) {
            addCriterion("parent_id <", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idLessThanOrEqualTo(Integer value) {
            addCriterion("parent_id <=", value, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idIn(List<Integer> values) {
            addCriterion("parent_id in", values, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotIn(List<Integer> values) {
            addCriterion("parent_id not in", values, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idBetween(Integer value1, Integer value2) {
            addCriterion("parent_id between", value1, value2, "parent_id");
            return (Criteria) this;
        }

        public Criteria andParent_idNotBetween(Integer value1, Integer value2) {
            addCriterion("parent_id not between", value1, value2, "parent_id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kind
     *
     * @mbggenerated do_not_delete_during_merge Wed Jun 05 13:46:39 CST 2013
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table kind
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}