package test.model;

public class Kind {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind.kind_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private Integer kind_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind.kind_name
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private String kind_name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind.is_parent
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private Boolean is_parent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kind.parent_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private Integer parent_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind.kind_id
     *
     * @return the value of kind.kind_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public Integer getKind_id() {
        return kind_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind.kind_id
     *
     * @param kind_id the value for kind.kind_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setKind_id(Integer kind_id) {
        this.kind_id = kind_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind.kind_name
     *
     * @return the value of kind.kind_name
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public String getKind_name() {
        return kind_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind.kind_name
     *
     * @param kind_name the value for kind.kind_name
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setKind_name(String kind_name) {
        this.kind_name = kind_name == null ? null : kind_name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind.is_parent
     *
     * @return the value of kind.is_parent
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public Boolean getIs_parent() {
        return is_parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind.is_parent
     *
     * @param is_parent the value for kind.is_parent
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setIs_parent(Boolean is_parent) {
        this.is_parent = is_parent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kind.parent_id
     *
     * @return the value of kind.parent_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public Integer getParent_id() {
        return parent_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kind.parent_id
     *
     * @param parent_id the value for kind.parent_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setParent_id(Integer parent_id) {
        this.parent_id = parent_id;
    }
}