package test.model;

public class Picture {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pict_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private Integer pict_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.file
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private String file;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.name
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture.pictureSet_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private Integer pictureSet_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pict_id
     *
     * @return the value of picture.pict_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public Integer getPict_id() {
        return pict_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pict_id
     *
     * @param pict_id the value for picture.pict_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setPict_id(Integer pict_id) {
        this.pict_id = pict_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.file
     *
     * @return the value of picture.file
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public String getFile() {
        return file;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.file
     *
     * @param file the value for picture.file
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setFile(String file) {
        this.file = file == null ? null : file.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.name
     *
     * @return the value of picture.name
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.name
     *
     * @param name the value for picture.name
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture.pictureSet_id
     *
     * @return the value of picture.pictureSet_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public Integer getPictureSet_id() {
        return pictureSet_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture.pictureSet_id
     *
     * @param pictureSet_id the value for picture.pictureSet_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setPictureSet_id(Integer pictureSet_id) {
        this.pictureSet_id = pictureSet_id;
    }
}