package test.model;

public class PictureSet {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_set.ps_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private Integer ps_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_set.comm_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private Integer comm_id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_set.name
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column picture_set.cover_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    private Integer cover_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_set.ps_id
     *
     * @return the value of picture_set.ps_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public Integer getPs_id() {
        return ps_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_set.ps_id
     *
     * @param ps_id the value for picture_set.ps_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setPs_id(Integer ps_id) {
        this.ps_id = ps_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_set.comm_id
     *
     * @return the value of picture_set.comm_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public Integer getComm_id() {
        return comm_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_set.comm_id
     *
     * @param comm_id the value for picture_set.comm_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setComm_id(Integer comm_id) {
        this.comm_id = comm_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_set.name
     *
     * @return the value of picture_set.name
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_set.name
     *
     * @param name the value for picture_set.name
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column picture_set.cover_id
     *
     * @return the value of picture_set.cover_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public Integer getCover_id() {
        return cover_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column picture_set.cover_id
     *
     * @param cover_id the value for picture_set.cover_id
     *
     * @mbggenerated Wed Jun 05 13:46:39 CST 2013
     */
    public void setCover_id(Integer cover_id) {
        this.cover_id = cover_id;
    }
}